const messages = [
  {
    id: 1,
    sender: "Jessica Gilmore",
    message: "Hey, how are you?",
    time: "23:40",
    avatar: "/profile-1.jpg",
  },
  {
    id: 2,
    sender: "Mikassa Ackerman",
    message: "Where are you?",
    time: "13:00",
    avatar: "/profile-2.jpg",
  },
  {
    id: 3,
    sender: "Eren Yeager",
    message: "Hey, how are you?",
    time: "10:40",
    avatar: "/profile-3.jpg",
  },
  {
    id: 4,
    sender: "Mikassa Ackerman",
    message: "Where are you?",
    time: "13:00",
    avatar: "/profile-4.jpg",
  },
  {
    id: 5,
    sender: "Eren Yeager",
    message: "Hey, how are you?",
    time: "10:40",
    avatar: "/profile-5.jpg",
  },
];

const posts = [
  {
    id: 1,
    firstName: "Jessica",
    lastName: "Gilmore",
    avatar: "/profile-1.jpg",
    time: "20 mins ago",
    text: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image: "/post-1.jpg",
  },
  {
    id: 2,
    firstName: "Michael",
    lastName: "Smith",
    avatar: "/profile-2.jpg",
    time: "20 mins ago",
    text: "Happy Sunday, everyone! 🌞 Enjoying a relaxing day with my favorite book.",
    image: "/post-2.jpg",
  },
  {
    id: 3,
    firstName: "Emily",
    lastName: "Johnson",
    avatar: "/profile-3.jpg",
    time: "20 mins ago",
    text: "Just finished a fantastic workout at the gym! Feeling pumped and energized! 💪🏋️‍♀️",
    image: "/post-3.jpg",
  },
  {
    id: 4,
    firstName: "David",
    lastName: "Lee",
    avatar: "/profile-4.jpg",
    time: "20 mins ago",
    text: "Exploring the beautiful countryside this weekend. Nature is truly amazing! 🌳🍃",
    image: "/post-4.jpg",
  },
  {
    id: 5,
    firstName: "Sophia",
    lastName: "Wang",
    avatar: "/profile-5.jpg",
    time: "20 mins ago",
    text: "Having a delightful lunch with friends at my favorite restaurant! 🍔🍟",
    image: "/post-5.jpg",
  },
  {
    id: 6,
    firstName: "James",
    lastName: "Davis",
    avatar: "/profile-6.jpg",
    time: "20 mins ago",
    text: "Just adopted this adorable little furball! Meet my new best friend, Max! 🐶💕",
    image: "/post-6.jpg",
  },
];
export { messages, posts };
